services:
  mysql:
    image: mysql:8.0
    container_name: ticketing_db
    environment:
      MYSQL_DATABASE: ticketing_mundial
      MYSQL_USER: ticketing_user
      MYSQL_PASSWORD: ticketing_pass
      MYSQL_ROOT_PASSWORD: root_pass
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "3307:3306"
    volumes:
      - ./sql/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
      - ./sql/02_inserts.sql:/docker-entrypoint-initdb.d/02_inserts.sql:ro
    tmpfs:
      - /var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uticketing_user", "-pticketing_pass"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: ticketing_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql://ticketing_user:ticketing_pass@mysql:3306/ticketing_mundial
      AUTH0_DOMAIN: ${AUTH0_DOMAIN:-dev-v621pgnudibv25if.us.auth0.com}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE:-https://ticketing-mundial/api}
      AUTH0_ALGORITHMS: RS256
      AUTH0_NAMESPACE: ${AUTH0_NAMESPACE:-https://ticketing-mundial}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID:-OiKYRWbFFR1vMkfoVFvoFjpgugpDbyVT}
      CORS_ORIGINS: http://localhost:5173
    depends_on:
      mysql:
        condition: service_healthy
